"""add explore_node code and cultural_item_id

Revision ID: cd444050f9bb
Revises: f758b2f08e80
Create Date: 2026-08-26 17:19:57.462949

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "cd444050f9bb"
down_revision: str | Sequence[str] | None = "f758b2f08e80"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "explore_node",
        sa.Column(
            "code", sa.String(length=64), nullable=True, comment="二维码/NFC 码值（扫码识别用）"
        ),
    )
    op.add_column(
        "explore_node",
        sa.Column("cultural_item_id", sa.String(), nullable=True, comment="绑定解锁的文化卡片 ID"),
    )
    op.create_unique_constraint(op.f("uq_explore_node_code"), "explore_node", ["code"])
    op.create_foreign_key(
        op.f("fk_explore_node_cultural_item_id_cultural_item"),
        "explore_node",
        "cultural_item",
        ["cultural_item_id"],
        ["id"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_explore_node_cultural_item_id_cultural_item"), "explore_node", type_="foreignkey"
    )
    op.drop_constraint(op.f("uq_explore_node_code"), "explore_node", type_="unique")
    op.drop_column("explore_node", "cultural_item_id")
    op.drop_column("explore_node", "code")
    # ### end Alembic commands ###
