"""initial schema

Revision ID: f758b2f08e80
Revises:
Create Date: 2026-08-26 16:47:42.164019

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f758b2f08e80"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "achievement",
        sa.Column("name", sa.String(length=128), nullable=False, comment="成就名称"),
        sa.Column("description", sa.String(length=512), nullable=True, comment="描述"),
        sa.Column("icon_url", sa.String(length=512), nullable=True, comment="图标 URL"),
        sa.Column("unlock_condition", sa.String(length=255), nullable=True, comment="解锁条件"),
        sa.Column("id", sa.String(), nullable=False, comment="主键 UUID"),
        sa.Column("created_at", sa.DateTime(), nullable=False, comment="创建时间"),
        sa.Column("updated_at", sa.DateTime(), nullable=False, comment="更新时间"),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_achievement")),
    )
    op.create_table(
        "admin_user",
        sa.Column("username", sa.String(length=64), nullable=False, comment="用户名"),
        sa.Column("hashed_password", sa.String(length=255), nullable=False, comment="密码哈希"),
        sa.Column("is_active", sa.Boolean(), nullable=False, comment="是否启用"),
        sa.Column("id", sa.String(), nullable=False, comment="主键 UUID"),
        sa.Column("created_at", sa.DateTime(), nullable=False, comment="创建时间"),
        sa.Column("updated_at", sa.DateTime(), nullable=False, comment="更新时间"),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_admin_user")),
        sa.UniqueConstraint("username", name=op.f("uq_admin_user_username")),
    )
    op.create_table(
        "chapter",
        sa.Column("name", sa.String(length=128), nullable=False, comment="章节名称"),
        sa.Column("description", sa.Text(), nullable=True, comment="章节介绍"),
        sa.Column("sort_order", sa.Integer(), nullable=False, comment="排序"),
        sa.Column("id", sa.String(), nullable=False, comment="主键 UUID"),
        sa.Column("created_at", sa.DateTime(), nullable=False, comment="创建时间"),
        sa.Column("updated_at", sa.DateTime(), nullable=False, comment="更新时间"),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_chapter")),
    )
    op.create_table(
        "cultural_item",
        sa.Column("name", sa.String(length=128), nullable=False, comment="名称"),
        sa.Column("pinyin", sa.String(length=128), nullable=True, comment="拼音"),
        sa.Column(
            "category",
            sa.Enum("CLOTHING", "PATTERN", "MUSIC", "CUISINE", "CRAFT", name="culturalcategory"),
            nullable=False,
            comment="分类",
        ),
        sa.Column(
            "rarity",
            sa.Enum("COMMON", "RARE", "LEGENDARY", name="rarity"),
            nullable=False,
            comment="稀有度",
        ),
        sa.Column("origin", sa.String(length=255), nullable=True, comment="发源地"),
        sa.Column("material", sa.String(length=255), nullable=True, comment="材质"),
        sa.Column("symbolism", sa.String(length=255), nullable=True, comment="象征意义"),
        sa.Column("description", sa.Text(), nullable=True, comment="详细介绍"),
        sa.Column("image_url", sa.String(length=512), nullable=True, comment="图片 URL"),
        sa.Column("audio_url", sa.String(length=512), nullable=True, comment="音频 URL"),
        sa.Column("sort_order", sa.Integer(), nullable=False, comment="排序"),
        sa.Column("is_published", sa.Boolean(), nullable=False, comment="是否发布"),
        sa.Column("id", sa.String(), nullable=False, comment="主键 UUID"),
        sa.Column("created_at", sa.DateTime(), nullable=False, comment="创建时间"),
        sa.Column("updated_at", sa.DateTime(), nullable=False, comment="更新时间"),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_cultural_item")),
    )
    op.create_table(
        "product_category",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False, comment="主键"),
        sa.Column("name", sa.String(length=64), nullable=False, comment="分类名"),
        sa.Column("icon_url", sa.String(length=512), nullable=True, comment="分类图标"),
        sa.Column("sort_order", sa.Integer(), nullable=False, comment="排序"),
        sa.Column("is_enabled", sa.Boolean(), nullable=False, comment="是否启用"),
        sa.Column("created_at", sa.DateTime(), nullable=False, comment="创建时间"),
        sa.Column("updated_at", sa.DateTime(), nullable=False, comment="更新时间"),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_product_category")),
    )
    op.create_table(
        "user",
        sa.Column("openid", sa.String(length=64), nullable=True, comment="微信 openid"),
        sa.Column("phone", sa.String(length=20), nullable=True, comment="手机号"),
        sa.Column("nickname", sa.String(length=64), nullable=True, comment="昵称"),
        sa.Column("avatar_url", sa.String(length=512), nullable=True, comment="头像 URL"),
        sa.Column("level", sa.Integer(), nullable=False, comment="等级"),
        sa.Column("title", sa.String(length=64), nullable=True, comment="称号"),
        sa.Column("points", sa.Integer(), nullable=False, comment="积分"),
        sa.Column("id", sa.String(), nullable=False, comment="主键 UUID"),
        sa.Column("created_at", sa.DateTime(), nullable=False, comment="创建时间"),
        sa.Column("updated_at", sa.DateTime(), nullable=False, comment="更新时间"),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user")),
        sa.UniqueConstraint("openid", name=op.f("uq_user_openid")),
        sa.UniqueConstraint("phone", name=op.f("uq_user_phone")),
    )
    op.create_table(
        "wardrobe_item",
        sa.Column("name", sa.String(length=128), nullable=False, comment="名称"),
        sa.Column(
            "category",
            sa.Enum("CLOTHES", "HEADWEAR", "ACCESSORIES", "SKINS", name="wardrobecategory"),
            nullable=False,
            comment="分类",
        ),
        sa.Column(
            "rarity",
            sa.Enum("COMMON", "RARE", "LEGENDARY", name="rarity"),
            nullable=False,
            comment="稀有度",
        ),
        sa.Column("description", sa.String(length=512), nullable=True, comment="描述"),
        sa.Column("image_url", sa.String(length=512), nullable=True, comment="图片 URL"),
        sa.Column("total_fragments", sa.Integer(), nullable=False, comment="合成所需碎片数"),
        sa.Column("sort_order", sa.Integer(), nullable=False, comment="排序"),
        sa.Column("id", sa.String(), nullable=False, comment="主键 UUID"),
        sa.Column("created_at", sa.DateTime(), nullable=False, comment="创建时间"),
        sa.Column("updated_at", sa.DateTime(), nullable=False, comment="更新时间"),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_wardrobe_item")),
    )
    op.create_table(
        "explore_node",
        sa.Column("chapter_id", sa.String(), nullable=False, comment="章节 ID"),
        sa.Column("name", sa.String(length=128), nullable=False, comment="节点名称"),
        sa.Column("location", sa.String(length=255), nullable=True, comment="地点"),
        sa.Column("description", sa.Text(), nullable=True, comment="节点介绍"),
        sa.Column("preview_image_url", sa.String(length=512), nullable=True, comment="预览图"),
        sa.Column("sort_order", sa.Integer(), nullable=False, comment="排序"),
        sa.Column("puzzle_image_url", sa.String(length=512), nullable=True, comment="拼图底图"),
        sa.Column("puzzle_pieces", sa.Integer(), nullable=False, comment="拼图块数"),
        sa.Column("id", sa.String(), nullable=False, comment="主键 UUID"),
        sa.Column("created_at", sa.DateTime(), nullable=False, comment="创建时间"),
        sa.Column("updated_at", sa.DateTime(), nullable=False, comment="更新时间"),
        sa.ForeignKeyConstraint(
            ["chapter_id"], ["chapter.id"], name=op.f("fk_explore_node_chapter_id_chapter")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_explore_node")),
    )
    op.create_table(
        "order",
        sa.Column(
            "order_no", sa.String(length=32), nullable=False, comment="订单号 SY20260818xxxx"
        ),
        sa.Column("user_id", sa.String(), nullable=False, comment="用户 ID"),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING_PAYMENT",
                "PAID",
                "SHIPPED",
                "COMPLETED",
                "CANCELLED",
                "REFUNDING",
                "REFUNDED",
                name="orderstatus",
            ),
            nullable=False,
            comment="订单状态",
        ),
        sa.Column(
            "total_amount", sa.Numeric(precision=10, scale=2), nullable=False, comment="商品总额"
        ),
        sa.Column(
            "freight_amount", sa.Numeric(precision=10, scale=2), nullable=False, comment="运费"
        ),
        sa.Column(
            "pay_amount", sa.Numeric(precision=10, scale=2), nullable=False, comment="实付金额"
        ),
        sa.Column(
            "address_snapshot", sa.JSON(), nullable=True, comment="下单地址快照（收货人/电话/地址）"
        ),
        sa.Column("remark", sa.String(length=255), nullable=True, comment="买家留言"),
        sa.Column("paid_at", sa.DateTime(), nullable=True, comment="支付时间"),
        sa.Column("shipped_at", sa.DateTime(), nullable=True, comment="发货时间"),
        sa.Column("completed_at", sa.DateTime(), nullable=True, comment="完成时间"),
        sa.Column("cancelled_at", sa.DateTime(), nullable=True, comment="取消时间"),
        sa.Column("cancel_reason", sa.String(length=255), nullable=True, comment="取消/关闭原因"),
        sa.Column("expired_at", sa.DateTime(), nullable=True, comment="支付过期时间（下单+30min）"),
        sa.Column("id", sa.String(), nullable=False, comment="主键 UUID"),
        sa.Column("created_at", sa.DateTime(), nullable=False, comment="创建时间"),
        sa.Column("updated_at", sa.DateTime(), nullable=False, comment="更新时间"),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], name=op.f("fk_order_user_id_user")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_order")),
        sa.UniqueConstraint("order_no", name=op.f("uq_order_order_no")),
    )
    op.create_table(
        "product",
        sa.Column("category_id", sa.Integer(), nullable=False, comment="分类 ID"),
        sa.Column("name", sa.String(length=128), nullable=False, comment="商品名"),
        sa.Column("subtitle", sa.String(length=255), nullable=True, comment="副标题"),
        sa.Column("main_image", sa.String(length=512), nullable=True, comment="主图"),
        sa.Column("images", sa.JSON(), nullable=True, comment="详情图列表"),
        sa.Column("description", sa.Text(), nullable=True, comment="图文详情"),
        sa.Column("is_blind_box", sa.Boolean(), nullable=False, comment="是否盲盒类商品"),
        sa.Column(
            "blind_box_odds",
            sa.JSON(),
            nullable=True,
            comment="盲盒款式概率公示 [{sku_id, name, probability}]",
        ),
        sa.Column(
            "status",
            sa.Enum("DRAFT", "ON_SALE", "OFF_SALE", name="productstatus"),
            nullable=False,
            comment="商品状态",
        ),
        sa.Column(
            "total_stock", sa.Integer(), nullable=False, comment="总库存（冗余=SUM sku.stock）"
        ),
        sa.Column("total_sold", sa.Integer(), nullable=False, comment="总销量"),
        sa.Column("id", sa.String(), nullable=False, comment="主键 UUID"),
        sa.Column("created_at", sa.DateTime(), nullable=False, comment="创建时间"),
        sa.Column("updated_at", sa.DateTime(), nullable=False, comment="更新时间"),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["product_category.id"],
            name=op.f("fk_product_category_id_product_category"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_product")),
    )
    op.create_table(
        "user_achievement",
        sa.Column("user_id", sa.String(), nullable=False, comment="用户 ID"),
        sa.Column("achievement_id", sa.String(), nullable=False, comment="成就 ID"),
        sa.Column("id", sa.String(), nullable=False, comment="主键 UUID"),
        sa.Column("created_at", sa.DateTime(), nullable=False, comment="创建时间"),
        sa.Column("updated_at", sa.DateTime(), nullable=False, comment="更新时间"),
        sa.ForeignKeyConstraint(
            ["achievement_id"],
            ["achievement.id"],
            name=op.f("fk_user_achievement_achievement_id_achievement"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["user.id"], name=op.f("fk_user_achievement_user_id_user")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user_achievement")),
        sa.UniqueConstraint("user_id", "achievement_id", name="uq_user_achievement_user_ach"),
    )
    op.create_table(
        "user_address",
        sa.Column("user_id", sa.String(), nullable=False, comment="用户 ID"),
        sa.Column("receiver", sa.String(length=64), nullable=False, comment="收货人"),
        sa.Column("phone", sa.String(length=20), nullable=False, comment="手机号"),
        sa.Column("province", sa.String(length=32), nullable=False, comment="省"),
        sa.Column("city", sa.String(length=32), nullable=False, comment="市"),
        sa.Column("district", sa.String(length=32), nullable=False, comment="区"),
        sa.Column("detail", sa.String(length=255), nullable=False, comment="详细地址"),
        sa.Column("is_default", sa.Boolean(), nullable=False, comment="默认地址"),
        sa.Column("id", sa.String(), nullable=False, comment="主键 UUID"),
        sa.Column("created_at", sa.DateTime(), nullable=False, comment="创建时间"),
        sa.Column("updated_at", sa.DateTime(), nullable=False, comment="更新时间"),
        sa.ForeignKeyConstraint(
            ["user_id"], ["user.id"], name=op.f("fk_user_address_user_id_user")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user_address")),
    )
    op.create_table(
        "user_collection",
        sa.Column("user_id", sa.String(), nullable=False, comment="用户 ID"),
        sa.Column("cultural_item_id", sa.String(), nullable=False, comment="文化条目 ID"),
        sa.Column("id", sa.String(), nullable=False, comment="主键 UUID"),
        sa.Column("created_at", sa.DateTime(), nullable=False, comment="创建时间"),
        sa.Column("updated_at", sa.DateTime(), nullable=False, comment="更新时间"),
        sa.ForeignKeyConstraint(
            ["cultural_item_id"],
            ["cultural_item.id"],
            name=op.f("fk_user_collection_cultural_item_id_cultural_item"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["user.id"], name=op.f("fk_user_collection_user_id_user")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user_collection")),
        sa.UniqueConstraint("user_id", "cultural_item_id", name="uq_user_collection_user_item"),
    )
    op.create_table(
        "user_wardrobe",
        sa.Column("user_id", sa.String(), nullable=False, comment="用户 ID"),
        sa.Column("wardrobe_item_id", sa.String(), nullable=False, comment="衣橱道具 ID"),
        sa.Column("fragments", sa.Integer(), nullable=False, comment="已收集碎片数"),
        sa.Column("is_completed", sa.Boolean(), nullable=False, comment="是否合成完成"),
        sa.Column("id", sa.String(), nullable=False, comment="主键 UUID"),
        sa.Column("created_at", sa.DateTime(), nullable=False, comment="创建时间"),
        sa.Column("updated_at", sa.DateTime(), nullable=False, comment="更新时间"),
        sa.ForeignKeyConstraint(
            ["user_id"], ["user.id"], name=op.f("fk_user_wardrobe_user_id_user")
        ),
        sa.ForeignKeyConstraint(
            ["wardrobe_item_id"],
            ["wardrobe_item.id"],
            name=op.f("fk_user_wardrobe_wardrobe_item_id_wardrobe_item"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user_wardrobe")),
        sa.UniqueConstraint("user_id", "wardrobe_item_id", name="uq_user_wardrobe_user_item"),
    )
    op.create_table(
        "payment",
        sa.Column("order_id", sa.String(), nullable=False, comment="订单 ID"),
        sa.Column(
            "transaction_id",
            sa.String(length=64),
            nullable=True,
            comment="微信支付订单号（回调回填）",
        ),
        sa.Column("prepay_id", sa.String(length=64), nullable=True, comment="预支付 ID"),
        sa.Column("amount", sa.Numeric(precision=10, scale=2), nullable=False, comment="支付金额"),
        sa.Column(
            "status",
            sa.Enum("PENDING", "SUCCESS", "FAILED", "REFUNDED", name="paystatus"),
            nullable=False,
            comment="支付状态",
        ),
        sa.Column("raw_notify", sa.JSON(), nullable=True, comment="微信回调原文（排障）"),
        sa.Column("paid_at", sa.DateTime(), nullable=True, comment="支付成功时间"),
        sa.Column("id", sa.String(), nullable=False, comment="主键 UUID"),
        sa.Column("created_at", sa.DateTime(), nullable=False, comment="创建时间"),
        sa.Column("updated_at", sa.DateTime(), nullable=False, comment="更新时间"),
        sa.ForeignKeyConstraint(["order_id"], ["order.id"], name=op.f("fk_payment_order_id_order")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_payment")),
        sa.UniqueConstraint("transaction_id", name=op.f("uq_payment_transaction_id")),
    )
    op.create_table(
        "product_sku",
        sa.Column("product_id", sa.String(), nullable=False, comment="商品 ID"),
        sa.Column(
            "specs", sa.JSON(), nullable=True, comment='规格组合 {"款式":"凤凰装","尺寸":"10cm"}'
        ),
        sa.Column("price", sa.Numeric(precision=10, scale=2), nullable=False, comment="售价（元）"),
        sa.Column("stock", sa.Integer(), nullable=False, comment="库存（下单预占，支付扣减）"),
        sa.Column("image", sa.String(length=512), nullable=True, comment="款式图"),
        sa.Column("id", sa.String(), nullable=False, comment="主键 UUID"),
        sa.Column("created_at", sa.DateTime(), nullable=False, comment="创建时间"),
        sa.Column("updated_at", sa.DateTime(), nullable=False, comment="更新时间"),
        sa.ForeignKeyConstraint(
            ["product_id"], ["product.id"], name=op.f("fk_product_sku_product_id_product")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_product_sku")),
    )
    op.create_table(
        "refund",
        sa.Column("order_id", sa.String(), nullable=False, comment="订单 ID"),
        sa.Column("refund_no", sa.String(length=32), nullable=False, comment="商户退款单号"),
        sa.Column(
            "refund_id", sa.String(length=64), nullable=True, comment="微信退款单号（回调回填）"
        ),
        sa.Column("amount", sa.Numeric(precision=10, scale=2), nullable=False, comment="退款金额"),
        sa.Column("reason", sa.String(length=255), nullable=True, comment="退款原因"),
        sa.Column(
            "status",
            sa.Enum("PROCESSING", "SUCCESS", "FAILED", name="refundstatus"),
            nullable=False,
            comment="退款状态",
        ),
        sa.Column("operator_id", sa.String(), nullable=True, comment="操作管理员 ID"),
        sa.Column("id", sa.String(), nullable=False, comment="主键 UUID"),
        sa.Column("created_at", sa.DateTime(), nullable=False, comment="创建时间"),
        sa.Column("updated_at", sa.DateTime(), nullable=False, comment="更新时间"),
        sa.ForeignKeyConstraint(
            ["operator_id"], ["admin_user.id"], name=op.f("fk_refund_operator_id_admin_user")
        ),
        sa.ForeignKeyConstraint(["order_id"], ["order.id"], name=op.f("fk_refund_order_id_order")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_refund")),
        sa.UniqueConstraint("refund_no", name=op.f("uq_refund_refund_no")),
    )
    op.create_table(
        "shipment",
        sa.Column("order_id", sa.String(), nullable=False, comment="订单 ID"),
        sa.Column("carrier", sa.String(length=64), nullable=True, comment="快递公司"),
        sa.Column("tracking_no", sa.String(length=64), nullable=True, comment="运单号"),
        sa.Column("shipped_at", sa.DateTime(), nullable=True, comment="发货时间"),
        sa.Column("id", sa.String(), nullable=False, comment="主键 UUID"),
        sa.Column("created_at", sa.DateTime(), nullable=False, comment="创建时间"),
        sa.Column("updated_at", sa.DateTime(), nullable=False, comment="更新时间"),
        sa.ForeignKeyConstraint(
            ["order_id"], ["order.id"], name=op.f("fk_shipment_order_id_order")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_shipment")),
    )
    op.create_table(
        "user_explore_progress",
        sa.Column("user_id", sa.String(), nullable=False, comment="用户 ID"),
        sa.Column("node_id", sa.String(), nullable=False, comment="探索节点 ID"),
        sa.Column(
            "status",
            sa.Enum("COMPLETED", "ACTIVE", "LOCKED", name="nodestatus"),
            nullable=False,
            comment="节点进度状态",
        ),
        sa.Column("completed_at", sa.DateTime(), nullable=True, comment="完成时间"),
        sa.Column("id", sa.String(), nullable=False, comment="主键 UUID"),
        sa.Column("created_at", sa.DateTime(), nullable=False, comment="创建时间"),
        sa.Column("updated_at", sa.DateTime(), nullable=False, comment="更新时间"),
        sa.ForeignKeyConstraint(
            ["node_id"],
            ["explore_node.id"],
            name=op.f("fk_user_explore_progress_node_id_explore_node"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["user.id"], name=op.f("fk_user_explore_progress_user_id_user")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user_explore_progress")),
        sa.UniqueConstraint("user_id", "node_id", name="uq_user_explore_progress_user_node"),
    )
    op.create_table(
        "cart_item",
        sa.Column("user_id", sa.String(), nullable=False, comment="用户 ID"),
        sa.Column("sku_id", sa.String(), nullable=False, comment="SKU ID"),
        sa.Column("quantity", sa.Integer(), nullable=False, comment="数量（1-99）"),
        sa.Column("checked", sa.Boolean(), nullable=False, comment="是否勾选结算"),
        sa.Column("id", sa.String(), nullable=False, comment="主键 UUID"),
        sa.Column("created_at", sa.DateTime(), nullable=False, comment="创建时间"),
        sa.Column("updated_at", sa.DateTime(), nullable=False, comment="更新时间"),
        sa.ForeignKeyConstraint(
            ["sku_id"], ["product_sku.id"], name=op.f("fk_cart_item_sku_id_product_sku")
        ),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], name=op.f("fk_cart_item_user_id_user")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_cart_item")),
        sa.UniqueConstraint("user_id", "sku_id", name="uq_cart_item_user_sku"),
    )
    op.create_table(
        "order_item",
        sa.Column("order_id", sa.String(), nullable=False, comment="订单 ID"),
        sa.Column("product_id", sa.String(), nullable=False, comment="商品 ID"),
        sa.Column("sku_id", sa.String(), nullable=False, comment="SKU ID"),
        sa.Column(
            "product_snapshot", sa.JSON(), nullable=True, comment="商品快照（名称/主图/规格/单价）"
        ),
        sa.Column("quantity", sa.Integer(), nullable=False, comment="数量"),
        sa.Column(
            "unit_price", sa.Numeric(precision=10, scale=2), nullable=False, comment="成交单价快照"
        ),
        sa.Column("subtotal", sa.Numeric(precision=10, scale=2), nullable=False, comment="小计"),
        sa.Column("id", sa.String(), nullable=False, comment="主键 UUID"),
        sa.Column("created_at", sa.DateTime(), nullable=False, comment="创建时间"),
        sa.Column("updated_at", sa.DateTime(), nullable=False, comment="更新时间"),
        sa.ForeignKeyConstraint(
            ["order_id"], ["order.id"], name=op.f("fk_order_item_order_id_order")
        ),
        sa.ForeignKeyConstraint(
            ["product_id"], ["product.id"], name=op.f("fk_order_item_product_id_product")
        ),
        sa.ForeignKeyConstraint(
            ["sku_id"], ["product_sku.id"], name=op.f("fk_order_item_sku_id_product_sku")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_order_item")),
    )
    op.create_table(
        "stock_log",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False, comment="主键"),
        sa.Column("sku_id", sa.String(), nullable=False, comment="SKU ID"),
        sa.Column("delta", sa.Integer(), nullable=False, comment="变动量（正增负减）"),
        sa.Column(
            "reason",
            sa.Enum("RESERVE", "DEDUCT", "RELEASE", "RESTOCK", name="stocklogreason"),
            nullable=False,
            comment="变动原因",
        ),
        sa.Column("order_no", sa.String(length=32), nullable=True, comment="关联订单号"),
        sa.Column("created_at", sa.DateTime(), nullable=False, comment="时间"),
        sa.ForeignKeyConstraint(
            ["sku_id"], ["product_sku.id"], name=op.f("fk_stock_log_sku_id_product_sku")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_stock_log")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("stock_log")
    op.drop_table("order_item")
    op.drop_table("cart_item")
    op.drop_table("user_explore_progress")
    op.drop_table("shipment")
    op.drop_table("refund")
    op.drop_table("product_sku")
    op.drop_table("payment")
    op.drop_table("user_wardrobe")
    op.drop_table("user_collection")
    op.drop_table("user_address")
    op.drop_table("user_achievement")
    op.drop_table("product")
    op.drop_table("order")
    op.drop_table("explore_node")
    op.drop_table("wardrobe_item")
    op.drop_table("user")
    op.drop_table("product_category")
    op.drop_table("cultural_item")
    op.drop_table("chapter")
    op.drop_table("admin_user")
    op.drop_table("achievement")
    # ### end Alembic commands ###
